apiVersion: v1
kind: Service
metadata:
  name: async-service-monitor
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTP
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: traffic-port
spec:
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
