apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "async-service-monitor.fullname" . }}-config
  labels:
    {{- include "async-service-monitor.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |
{{ .Values.config.content | indent 4 }}
