apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: async-service-monitor
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: async-service-monitor
      app.kubernetes.io/component: control-plane
