apiVersion: v1
kind: Service
metadata:
  name: async-service-monitor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: async-service-monitor
    app.kubernetes.io/component: control-plane
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http
